### ISSUE TITLE
multilibrary: BPL asks for card often

### ISSUE THREAD

**Issue by daryanypl** [NYPL-Simplified/Simplified-iOS#511] opened 2016-12-23 00:43 UTC
I'm on test ipad.  I have tester account # put in for NYPL, and am using my personal card to log into BPL.  I can download NYPL books fine.  When I log into BPL from the account settings, I have no error message.  When I try to get a book from the BPL catalog, I get a dialog box asking me to log in.  I log in again, and have no error message (am allowed in).  But when I try to get the book, the login window pops up again.

I haven't used my BPL card in a few months.  Maybe there's something off with it.  If so, I'd expect to see an error message.
(Darya)

**Comment by aferditamuriqi** [comment] 2016-12-23 02:31
Thank you @daryanypl, can you send me your bel barcode and pin? So i can evaluate what the issue is.

**Comment by gioneill** [comment] 2017-01-20 18:30
Did this end up being related to the fact that even wrong username/password combos were appearing to log in? It's likely now this is resolved.

**Comment by aferditamuriqi** [comment] 2017-03-18 03:32
closing this, as it was not reproduced again.

**Closed by aferditamuriqi** 2017-03-18 03:32 UTC
