### ISSUE TITLE
Rendering engine freeze

### ISSUE THREAD

**Issue by leonardr** [NYPL-Simplified/Simplified-iOS#436] opened 2016-07-25 12:32 UTC
Report from patron:

_I was reading a chapter in the new Library of America version of Henry James's autobiography (one of My Books) -- and a page got stuck in mid-curl._

_It won't move any further. I tried all kinds of tapping and swiping. The page shows, with the curl rolling on an angle from upper right, and a small part of the upper right of the next page showing._

_I just looked at SimplyE again, and the page has changed to the opening page of the essay. However, it's still stuck with the same curl!_

The patron eventually fixed this problem by power-cycling their device.

I don't know which platform this is on. I have a query out to the patron. I'm filing this under iOS because that's the most common.

**Comment by winniequinn** [comment] 2016-08-15 14:53
This issue is caused by a part of the app that is going to be leveled with the new renderer. As such, I'm going to close this because we're never going to fix this issue directly.

**Closed by winniequinn** 2016-08-15 14:53 UTC
Labels: invalid
